CREATE DATABASE lucreMais;
USE lucreMais;

CREATE TABLE usuario
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nomeUsuario VARCHAR(50) NOT NULL,
	email VARCHAR(150) NOT NULL,
	senha VARCHAR(50) NOT NULL,
	dataCadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dataAtualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   UNIQUE KEY unique_nomeUsuario(nomeUsuario)
);

CREATE TABLE fornecedor
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	idUsuario INT UNSIGNED NOT NULL,
	nomeFornecedor VARCHAR(50) NOT NULL,
	email VARCHAR(150) DEFAULT NULL,
	telefone VARCHAR(15) NOT NULL,
	cnpj VARCHAR(50) DEFAULT NULL,
	endereco VARCHAR(150) DEFAULT NULL,
	dataCadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dataAtualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UNIQUE KEY unique_nomeFornecedor (nomeFornecedor),
	UNIQUE KEY unique_cnpj (cnpj),
	CONSTRAINT fornecedor_ibfk_1 FOREIGN KEY (idUsuario) REFERENCES usuario (id) ON DELETE RESTRICT ON UPDATE CASCADE
	
);

CREATE TABLE categoria
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	idUsuario INT UNSIGNED NOT NULL,
	descricaoCategoria VARCHAR(250) NOT NULL,
	dataCadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dataAtualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT categoria_ibfk_1 FOREIGN KEY (idUsuario) REFERENCES usuario (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE item
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	idUsuario INT UNSIGNED NOT NULL,  
	idCategoria INT UNSIGNED NOT NULL,
	marca VARCHAR(50) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	quantidade DOUBLE NOT NULL,
	quantidadeMinima DOUBLE NOT NULL,
	unidadeMedida VARCHAR(10) NOT NULL,
	dataCadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	dataAtualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
	CONSTRAINT item_ibfk_1 FOREIGN KEY (idUsuario) REFERENCES usuario (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT item_ibfk_3 FOREIGN KEY (idCategoria) REFERENCES categoria (id) ON DELETE RESTRICT ON UPDATE CASCADE	  
);

CREATE TABLE estoque
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	idUsuario INT UNSIGNED NOT NULL,
	idFornecedor INT UNSIGNED NOT NULL,
	idItem INT UNSIGNED NOT NULL,
	quantidade DOUBLE NOT NULL,
	preco DOUBLE NOT NULL,
	lote INT NOT NULL,
	statusItem ENUM('0', '1') DEFAULT '1' COMMENT '0 - Inativo, 1 - Ativo',
	dataCadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	dataAtualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
	CONSTRAINT estoque_ibfk_1 FOREIGN KEY (idUsuario) REFERENCES usuario (id) ON DELETE RESTRICT ON UPDATE CASCADE, 
	CONSTRAINT estoque_ibfk_2 FOREIGN KEY (idFornecedor) REFERENCES fornecedor (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT estoque_ibfk_3 FOREIGN KEY (idItem) REFERENCES item (id) ON DELETE RESTRICT ON UPDATE CASCADE 
);
