CREATE DATABASE lucreMais;
USE lucreMais;

CREATE TABLE usuario
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nomeUsuario VARCHAR(50) NOT NULL,
	email VARCHAR(150) NOT NULL,
	senha VARCHAR(50) NOT NULL,
	UNIQUE KEY unique_nomeUsuario (nomeUsuario)
);

CREATE TABLE item
(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	idUsuario INT UNSIGNED NOT NULL,
	nome VARCHAR(50) NOT NULL,
	quantidade INT NOT NULL,
	unidadeMedida VARCHAR(10) NOT NULL,
	preco DOUBLE NOT NULL,
	quantidadeMinima INT NOT NULL,
	lote INT NOT NULL,
	CONSTRAINT item_ibfk_1 FOREIGN KEY (idUsuario) REFERENCES usuario (id) ON DELETE RESTRICT ON UPDATE CASCADE 	  
);
